apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rallyetool-mediafiles-pvc
  namespace: rallyetool
  labels:
    app: rallyetool
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
