apiVersion: v1
kind: ConfigMap
metadata:
    name: rallyetool-config
    labels:
        app: rallyetool
    namespace: rallyetool
data:
    DJANGO_ALLOWED_HOSTS: 'rallye.frank.elsinga.de'
    DEBUG: 'False'
