apiVersion: v1
kind: PersistentVolume
metadata:
  name: rallyetool-pv
  namespace: rallyetool
  labels:
    app: rallyetool
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data/rallyetool'
